# Generated by Django 6.0.5 on 2026-07-03 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_book_alter_library_options_library_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('book_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='catalog.bookinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'overdue'])), fields=('user', 'book_inventory'), name='unique_active_borrow_per_user_and_inventory')],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('book_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='catalog.bookinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book_inventory'), name='unique_waitlist_entry')],
            },
        ),
    ]
