# Generated by Django 6.0.5 on 2026-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='library',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('age_rating', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='catalog.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='catalog.library')),
            ],
            options={'ordering': ['library__name', 'book__title']},
        ),
    ]
